import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class CopyrightBar extends StatelessWidget {
  const CopyrightBar({
    Key key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(
      height: 40,
      child: Center(
        child: Text.rich(TextSpan(text: 'Generated by ', children: [
          TextSpan(
              text: 'pana_visual v0.0.1',
              style: TextStyle(color: Theme.of(context).primaryColor))
        ])),
      ),
    );
  }
}
